### ISSUE TITLE
pagebreak with table rowspan not created correctly

### ISSUE THREAD

**Issue by Shinseiki86** [dompdf/dompdf#1388]
I have a table with merged cells in several rows, but when I use dompdf and performs a page break, the cells are not created correctly.

How can I correct it?
Thanks.

Table: https://jsfiddle.net/shinseiki86/24LL3fd5/

Result: 
![image](https://cloud.githubusercontent.com/assets/22685115/23094984/74f9dcd8-f5d0-11e6-9d6c-cebfd720734a.png)

**Comment by bsweeney** [comment]
I'm fairly certain there's an existing issue for this ... but I couldn't find it in a quick search.

**Comment by Shinseiki86** [comment]
Right! I have encountered some similar issues, but no solution.

https://sourceforge.net/p/dompdf/bugs/39/

**Comment by bsweeney** [comment]
Maybe #232 is most appropriate, which points to #55.

**Comment by prtk418** [comment]
is this still unsolved?

**Comment by amayer-glei** [comment]
> 
> 
> is this still unsolved? i am facing same issue

yes still broken... switched to wkhtlmpdf now.

**Comment by Ajahuanex** [comment]
> > is this still unsolved? i am facing same issue
> 
> yes still broken... switched to wkhtlmpdf now.

but, wkhtmlpdf don't work in shared hosting.

**Comment by simonberger** [comment]
Minimum example to test the problem (A4, landscape)

```
<html>
<head>
	<style>
		table, td, th {
			border: 1px solid black;
		}
	</style>
</head>
<body>
<table>
  <tbody>
    <tr>
		<td rowspan="3">1</td>
		<td>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br>2<br></td>
    </tr>
	<tr><td>3</td></tr>
	<tr><td>4<br>4<br>4<br></td></tr>
  </tbody>
</table>
</body>
</html>
```

Any active rowspan is not remembered on page breaks.
I currently debug this behavior but it is really deep in the renderer and/or decorator tasks.

**Comment by jonathanpmartins** [comment]
having the same problem here!

```page-break-inside: avoid;``` should work with ```tbody``` group tag.

**Comment by Jensovic** [comment]
Also here. I read that its a known issue that table row has to be on one page, but to not carry a rowspan to the next page is a severe bug. 

I did a debug query and it seems that the table structure (tablemap) is intact, its only that the rowspan is not remembered and cells are dropped in the wrong column. 

I think it would be possible to remember the rowspan with an temporary array and check this after the pagebreak to "skip" rowspanned cells on the next page.
Another solution would be to check if all rows of a rowspanned cell would fit onto the page, and if not, to pagebreak before that row with >1 rowspanned cell.

Who can help on that?
This bug is a showstopper :/

**Comment by Nuranto** [comment]
I confirm this issue is still present in last 1.0.2 version

**Comment by oldcrotchetydev** [comment]
Definitely still an issue.

**Comment by kanapes** [comment]
Thanks Brian - yes this issue looks like my problem #2676.

Have not seen this issue by using the searchengine, sorry for that.
I believe issue #1388 describes my problem very well but if you still need more test cases i can modifie my files from  issue #2676.

Just let me know

By the way, the start post of this issue makes me a little bit worried if i have a look on the date.
I do not want to push there is hope for a solution soon?

**Comment by bsweeney** [comment]
I can't promise a quick solution though I have been thinking about the problem a bit recently. Other more urgent issues have come up recently, however, so it'll have to wait until those are resolved for me to look at the problem.

Though, of course, anyone is welcome to try to solve the issue so maybe a kind soul will submit a PR.

**Comment by kanapes** [comment]
I just wanted to know which classes would be affected by this  or where is the doing for it contained?
Can you narrow down the range a bit. 

I also have a lot to do at the moment, but maybe one or the other time will come up.

**Comment by bsweeney** [comment]
I believe the issue is that when a row is paged the map of cells associated with the row is [reset](https://github.com/dompdf/dompdf/blob/v1.1.1/src/Cellmap.php#L726-L772), but it's not added back when building the cell map on the following page.

**Comment by kanapes** [comment]
how do you handle the output during creation. debugging is somewhat difficult that way.

**Comment by VMLearningHub** [comment]
`@foreach ($data['project_feature']['user_roles_data'] as $user_role_key => $user_roles)
                        @php
                            $user_role_value = $user_roles['name'];
                        @endphp
                            @foreach ($user_roles['main_features'] as $main_features_key => $main_features)
                            @php
                                $main_features_value = $main_features['name']
                            @endphp
                                
                                 @foreach ($main_features['sub_features'] as $sub_features_key => $sub_features)
                                 <tr>
                                    @if($user_role_value != "")
                                        <td style="border-top: 1px dotted #000; border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$user_role_value}}</td>
                                    @else
                                        <td style="border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$user_role_value}}</td>
                                    @endif
                                    @if($main_features_value != "")
                                        <td style="border-top: 1px dotted #000; border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$main_features_value}}</td>
                                    @else
                                        <td style="border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$main_features_value}}</td>
                                    @endif
                                    <td style='border: 1px dotted rgb(24, 24, 24);padding: 5px;font-size: 14px;color: #333333;'>{{ $sub_features['name'] }}</td>
                                     @php
                                         $user_role_value ="";
                                         $main_features_value="";
                                     @endphp
                                 </tr>
                                 
                                 @endforeach
                            @endforeach
                        @endforeach`
                        
                       
![image](https://user-images.githubusercontent.com/63444932/168016518-a7af1287-5ce4-4896-9682-3709bc0a707a.png)

**Comment by 233cy** [comment]
> ```
> @foreach ($data['project_feature']['user_roles_data'] as $user_role_key => $user_roles)
>                         @php
>                             $user_role_value = $user_roles['name'];
>                         @endphp
>                             @foreach ($user_roles['main_features'] as $main_features_key => $main_features)
>                             @php
>                                 $main_features_value = $main_features['name']
>                             @endphp
>                                 
>                                  @foreach ($main_features['sub_features'] as $sub_features_key => $sub_features)
>                                  <tr>
>                                     @if($user_role_value != "")
>                                         <td style="border-top: 1px dotted #000; border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$user_role_value}}</td>
>                                     @else
>                                         <td style="border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$user_role_value}}</td>
>                                     @endif
>                                     @if($main_features_value != "")
>                                         <td style="border-top: 1px dotted #000; border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$main_features_value}}</td>
>                                     @else
>                                         <td style="border-right: 1px dotted #000; padding: 5px; font-weight: 400; color: #333333;vertical-align: baseline;text-align: center;font-size: 14px;">{{$main_features_value}}</td>
>                                     @endif
>                                     <td style='border: 1px dotted rgb(24, 24, 24);padding: 5px;font-size: 14px;color: #333333;'>{{ $sub_features['name'] }}</td>
>                                      @php
>                                          $user_role_value ="";
>                                          $main_features_value="";
>                                      @endphp
>                                  </tr>
>                                  
>                                  @endforeach
>                             @endforeach
>                         @endforeach
> ```
> 
> 
>      
>   
> 
> ![图像](https://user-images.githubusercontent.com/63444932/168016518-a7af1287-5ce4-4896-9682-3709bc0a707a.png)

 How did you solve it

**Comment by 233cy** [comment]
@bsweeney I don't see a solution

**Comment by bsweeney** [comment]
There is no solution or work around for this issue yet.

**Comment by ilcavait** [comment]
I'm writing because I have a simil problem:

In a table when I write many rows in a cell, the program correctly break
page.

However, if the cell first cell has a rowspan and the long text is in
another cell, for example the third, the text in the new page has
written under first column and not third column.

I think about it is a similar problem of this issue. If I'm wrong, there
is a solution/workaround of my problem.


I use this occation to thank you for your fantastic program.

**Comment by bsweeney** [comment]
This is not planned for the 2.0.0 release (trying to wrap that one up). Hope to look at this a bit more for a near-future release, though.

**Comment by hasanmarzaq** [comment]
> This is not planned for the 2.0.0 release (trying to wrap that one up). Hope to look at this a bit more for a near-future release, though.

Has the case been solved?

**Comment by bsweeney** [comment]
Not solved yet, no.

**Comment by iBOT03** [comment]
@bsweeney 

> Not solved yet, no.

How about now, has the case been solved?
Because i had some issues/problem like this. I have condition using rowspan, but whenever it move to other page/page break, it will broken the table in pdf. I hope anyone will solve this problem soon..

**Comment by catalinmv** [comment]
> @bsweeney
> 
> > Not solved yet, no.
> 
> How about now, has the case been solved? Because i had some issues/problem like this. I have condition using rowspan, but whenever it move to other page/page break, it will broken the table in pdf. I hope anyone will solve this problem soon..

An update please, can this be solved soon? Looks like a pretty important bug to fix, in my opinion.

Thank you!

**Comment by catalinmv** [comment]
I supposed this doesn't have any chance of getting fixed any time soon, right?
Will finish my current project soon, an important part of it are the generated tables, some which of which have cells that span multiple rows. If this won't be fixed i will be forced to change to tcpdf, which is quite a bit of work from what i've seen in some initial tests. Any way that we can speed up the fixing of this issue?

**Comment by bsweeney** [comment]
I don't really have a sense of what this will take to fix but I'll take a look.

Also, what is your definition of "soon" because releases are sparse.

**Comment by Jensovic** [comment]
Nice to hear, 
   
  
    
   
  
   it would also keep my project running.
   
  
   There IS actually a workaround for that (most people dont know of this) but there is a guy that created a snippet to get around this.
   
  
    
   
   
   
    // If this is a nested table, prevent the page from breaking
    
   
                        if ($this->_in_table > 1) {
    
   
                            Helpers::dompdf_debug("page-break", "table: nested table");
    
    
   
                            return false;
    
   
                        }
    
   
                        // Prevent page breaking on rowspan cells. If child frames count of this table row less then column count of table , than it is likely that row touched by previous rowspan, prevent page from breaking
    
   
                        if($table && $table->get_cellmap() && $table->get_cellmap()->frame_exists_in_cellmap($frame) && $table->get_cellmap()->get_num_cols() > iterator_count($frame->get_children())) {
    
   
                            $cellmap = $table->get_cellmap();
    
   
                            $table_columns_count = $cellmap->get_num_cols();
    
    
   
                            $row_number = $cellmap->get_spanned_cells($frame)["rows"][0];
    
    
   
                            // Iterate through previous rows, to find and check spanned cell
    
   
                            $prev_row = $frame;
    
   
                            while($prev_row && $table_columns_count > iterator_count($prev_row->get_children())) {
    
   
                                $prev_row = $prev_row->get_prev_sibling();
    
   
                            }
    
    
   
                            // Check that we don't rollback all the way up to first row
    
   
                            if($prev_row) {
    
   
                                // Looking for spanned cell in row
    
   
                                foreach($prev_row->get_children() as $child) {
    
   
                                    $frame_rows = $cellmap->get_spanned_cells($child)["rows"];
    
   
                                    if($frame_rows && in_array($row_number, $frame_rows)) {
    
   
                                        Helpers::dompdf_debug("page-break", "table-row: contains verified spanned cell");
    
    
   
                                        return false;
    
   
                                    }
    
   
                                }
    
   
                            }
    
   
                        }
    
    
   
                        Helpers::dompdf_debug("page-break", "table-row/row-groups: break allowed");
    
    
   
                        return true;
    
   
   
   Hope that helps 
     
   Mit freundlichem GrußJens Horing___________________________Kontakt:Jens HoringJH Solution Consulting GmbHBüro Wiesbaden:Ahornstraße 265207 WiesbadenTel: 06122-705099Fax: 06122-705097Handy: 0177-7645431E-Mail: ***@***.***: www.horing.com 
   
   
   
    Brian Sweeney ***@***.***> hat am 08.02.2023 13:37 CET geschrieben:
    
   
     
    
   
     
    
     
   I don't really have a sense of what this will take to fix but I'll take a look. 
   Also, what is your definition of "soon" because releases are sparse.

**Comment by bsweeney** [comment]
Looks like you're referring to #2090? While that does improve the rendering I don't know that it's a good enough solution to the problem. Though it has been a while since I've reviewed the issue so it's possible that might be a good basis for a solution.

**Comment by catalinmv** [comment]
Sorry about the "soon", in my case it's the end of this month. Sorry for insisting with this, everything is perfect for our project with the library, except this bug. Sadly, there are tables generated that span multiple rows (sometimes a cell could even go on 3 pages, starts on page 1, occupies page 2 fully and ends on page 3). So the solution to not allow page-break is not good for us.
Thank you for your work on this project!

**Comment by Jensovic** [comment]
Hey Brian,thats why I posted this snipped. Sometimes its better not to start by 0JensVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Brian Sweeney ***@***.***> Datum: 09.02.23  00:12  (GMT+00:00) An: dompdf/dompdf ***@***.***> Cc: Jens Horing ***@***.***>, Comment ***@***.***> Betreff: Re: [dompdf/dompdf] Rowspanned TD element lost on page break (#1388) 
Looks like you're referring to #2090? While that does improve the rendering I don't know that it's a good enough solution to the problem. Though it has been a while since I've reviewed the issue so it's possible that might be a good basis for a solution.

**Comment by bsweeney** [comment]
> Sadly, there are tables generated that contain cells that span multiple rows (sometimes a cell could even go on 3 pages, starts on page 1, occupies page 2 fully and ends on page 3)

Would this cell have content as well? The case cited by the OP here is that a rowspanned cell that fully renders on the first page does not render at all on the next. In this scenario, the cell does not flow to the next page because it has been fully rendered. This issue is still challenging but the solution is more straightforward, and that's to ensure the cell flows alongside the rows it spans.

If the rowspanned cell has content that has to span multiple pages, that's a bit of a different issue. That's a more fundamental problem with Dompdf because when an element has to be split for rendering to a new page Dompdf does not return to the previous page to pick up where it left off. Though I have been pondering this issue, it's a more challenging problem to solve.

**Comment by catalinmv** [comment]
Yes, it has content, but most of the time it's not that much. But yes, there are cases where the content will have to be drawn on both pages, some of it on one page and the rest on the other. I would say that 95% of situation there is little content, that can be drawn on either page. Another issue could be vertical centering in this case and i have no idea how it would work.

**Comment by zainalawaludin** [comment]
has this problem been solved? i have the same problem

**Comment by 233cy** [comment]
> 

建议直接使用lampnick/doctron（docker服务 页面转图片或者pdf）搭建服务，然后在服务端通过mvc渲染出一个pdf，通过docker服务来生成图片pdf完成度可以达到98%。不过具体看每个人的具体需求

**Comment by zainalawaludin** [comment]
> 



> > 
> 
> 建议直接使用lampnick/doctron（docker服务 页面转图片或者pdf）搭建服务，然后在服务端通过mvc渲染出一个pdf，通过docker服务来生成图片pdf完成度可以达到98%。不过具体看每个人的具体需求

what does this mean ?

**Comment by 233cy** [comment]
> > 
> 
> > > 
> > 
> > 
> > 建议直接使用lampnick/doctron（docker服务 页面转图片或者pdf）搭建服务，然后在服务端通过mvc渲染出一个pdf，通过docker服务来生成图片pdf完成度可以达到98%。不过具体看每个人的具体需求
> 
> what does this mean ?

hub.docker.com Learn about the container lampnick/doctron

**Comment by bsweeney** [comment]
I started looking at this issue though I don't have a timeline for resolution yet.

**Comment by jonathanpmartins** [comment]
This is a 5 year problem. Would be very nice if it works like it logically supposed to. I'm using it since 2018 and it's very annoying to explain to my clients that this is a dependency problem, cannot do anything without more "time/money" input. So, it is, what it is... We are open source and the licence don't have any guarantees. If nobody is wanting to solve the problem, not even the clients when I talk about "money/time" input, I can just think that this is good enough as it is...
If you need help because time is short don't hesitate to call for it, I'm happy to help, so I think are others.
Every improvement will be so much appreciated!

**Comment by bsweeney** [comment]
As I said I'm working on this issue now, so I wouldn't recommend anybody put any time into it just yet. I have a [work-in-progress branch](https://github.com/dompdf/dompdf/tree/paging-updates) but right now it only addresses paging of tables and floats, not the rowspan issue. After reviewing current functionality I need to do a bit of refactoring. Once that's done I think I'll be able to address paging rowspans. At that point I'll open a PR and anyone who wants to help by testing the update and submitting feedback is more than welcome.

**Comment by jonathanpmartins** [comment]
I very much appreciate your work and I think other too. Thank you for your time spend in this project!
I would be happy to help testing the PR and give some feedback. This is great!

**Comment by iceaceice** [comment]
I have a temporary solution for this but I didn't use the row span instead I counted the row that my page will print here's my solution:

<table style="border-collapse: collapse; margin-left:auto; margin-right:auto; width:100%; font-size: 9pt; border: 1px solid black; margin-top: 30px;">
        <tr>
            <th class="text-uppercase align-center border-bottom" style="width: 17%; padding: 5px;">Date & Time</th>
            <th class="text-uppercase align-center border-left border-bottom" style="width: 11%; padding: 5px;">Treatment</th>
            <th class="text-uppercase align-center border-left border-bottom" style="width: 20%; padding: 5px;">Problem</th>
            <th class="text-uppercase align-center border-left border-bottom" style="width: 22%; padding: 5px;">Management</th>
            <th class="text-uppercase align-center border-left border-bottom" style="width: 30%; padding: 5px;">Nurse-in-Charge</th>
        </tr>

        <tbody>
            @if (!empty($problemList))
                @php
                    // Max row to print in next page of PDF
                    $next_page_max_row = 48;

                    // Default max row
                    $max_row = 34 - (count($diagnosis));

                    $row_counter = 0;

                    // Store the previous loop count
                    $prev_loop_count = 0;

                    // check if the page break;
                    $next_page = false;
                @endphp
                @foreach ($problemList as $list)

                    @php
                        // Convert to array
                        $problem = str_split($list->problem, 19);
                        $management = str_split($list->management, 20);

                        // Nurse in charge by column length counter
                        $prefix_len = (!empty($list->physician->consultant->gender) ? strlen($list->physician->consultant->gender == 'Male' ? 'Dr. ' : 'Dra. ') : 0);
                        $lname_len = (!empty($list->physician->consultant->last_name) ? strlen($list->physician->consultant->last_name) : 0);
                        $fname_len = (!empty($list->physician->consultant->first_name) ? strlen($list->physician->consultant->first_name): 0);
                        $sname_len = (!empty($list->physician->consultant->suffix_name) ? strlen($list->physician->consultant->suffix_name) : 0);
                        $mname_len = (!empty($list->physician->consultant->middle_name) ? strlen($list->physician->consultant->middle_name ): 0);

                        // Concating the the full name
                        $nurse_name_length = (!empty($list->physician->consultant) ? ($list->physician->consultant->gender == 'Male' ? 'Dr. ' : 'Dra. ') : "") .
                                             (!empty($list->physician->consultant->last_name) ? ($list->physician->consultant->last_name . (($lname_len + $fname_len + $prefix_len + 2) <= 31 ? ", " : ", \n")) : "") .
                                             (!empty($list->physician->consultant->first_name) ? ($list->physician->consultant->first_name . (!empty($list->physician->consultant->suffix_name) ? (" " . $list->physician->consultant->suffix_name . ($lname_len + $fname_len + $sname_len + $prefix_len + 4 <= 31 ? " " : "\n")) : ($lname_len + $fname_len + $prefix_len + 4 <= 31 ? " " : "\n"))) : " ") .
                                             (!empty($list->physician->consultant->middle_name) ? $list->physician->consultant->middle_name : "");

                        $nurse_full_name = explode("\n", $nurse_name_length);

                        $nurse_count = count($nurse_full_name);
                        $management_count = count($management);
                        $problem_count = count($problem);

                        $countArray = array(
                            "problem_name" => $problem_count,
                            "management_name" => $management_count,
                        );

                        // Determine the higher array count
                        $maxCount = max($countArray);
                        $temp_array_count = $maxCount;
                        $count_checker = $row_counter + $maxCount;

                    @endphp
                    @if ($count_checker <= $max_row)
                        <?php $row_counter += $temp_array_count ?>
                        @for ($i = 0; $i < $temp_array_count; $i++)
                            <tr>
                                <td class="align-center border-left {{ $i == 0 ? 'border-top' : '' }}" style="vertical-align: top; padding-left: 5px; white-space: nowrap;">{{ $i == 0 ? !empty($list->date_time) ? date('Y-m-d @ H:i', strtotime($list->date_time)) : "" : "" }}</td>
                                <td class="align-center border-left {{ $i == 0 ? 'border-top' : '' }}" style="vertical-align: top; padding-left: 5px; white-space: nowrap;">{{ $i == 0 ? !empty($list->treatment->name) ? $list->treatment->name : "" : "" }}</td>
                                <td class="align-top-left border-left {{ $i == 0 ? 'border-top' : '' }}" style="padding-left: 5px;">{{ isset($problem[$i]) ? $problem[$i] : "" }}</td>
                                <td class="align-top-left border-left {{ $i == 0 ? 'border-top' : '' }}" style="padding-left: 5px;">{{ isset($management[$i]) ? $management[$i] : "" }}</td>
                                <td class="align-center border-left {{ $i == 0 ? 'border-top' : '' }}" style="vertical-align: top; padding-left: 5px;">{{ isset($nurse_full_name[$i]) ? $nurse_full_name[$i] : "" }}</td>
                            </tr>
                        @endfor

                        {{-- Reset the row counter then add the next default max row  --}}
                        @if ($count_checker == $max_row)
                            <?php
                                $max_row = $next_page_max_row;
                                $row_counter = 0;
                            ?>
                        @endif
                    @else
                        @php
                            $temp_counter = 0;
                            $max_loop = ($max_row - $row_counter);
                            $next_page = true;
                            $max_row = $next_page_max_row;
                        @endphp

                        @for ($i = 0; $i < $temp_array_count; $i++)
                            <tr>
                                <td class="align-center border-left {{ $i == 0 ? 'border-top' : '' }}" style="vertical-align: top; padding-left: 5px; white-space: nowrap;">{{ $i == 0 ? !empty($list->date_time) ? date('Y-m-d @ H:i', strtotime($list->date_time)) : "" : "" }}</td>
                                <td class="align-center border-left {{ $i == 0 ? 'border-top' : '' }}" style="vertical-align: top; padding-left: 5px; white-space: nowrap;">{{ $i == 0 ? !empty($list->treatment->name) ? $list->treatment->name : "" : "" }}</td>
                                <td class="align-top-left border-left {{ $i == 0 ? 'border-top' : '' }}" style="padding-left: 5px;">{{ isset($problem[$i]) ? $problem[$i] : "" }}</td>
                                <td class="align-top-left border-left {{ $i == 0 ? 'border-top' : '' }}" style="padding-left: 5px;">{{ isset($management[$i]) ? $management[$i] : "" }}</td>
                                <td class="align-center border-left {{ $i == 0 ? 'border-top' : '' }}" style="padding-left: 5px;">{{ isset($nurse_full_name[$i]) ? $nurse_full_name[$i] : "" }}</td>
                            </tr>
                                
                            @if ($temp_counter == $max_loop)
                                @if ($next_page)
                                    <?php $prev_loop_count = $temp_array_count - $max_loop ?>
                                @endif
                            @endif

                            <?php $temp_counter++ ?>
                        @endfor

                        @if ($prev_loop_count && $next_page)
                            <?php
                                if ($prev_loop_count > $max_row) {
                                    $row_counter = ($prev_loop_count - $max_row);
                                    $prev_loop_count = 0;
                                }
                                elseif ($prev_loop_count == $max_row) {
                                    $row_counter = 0;
                                    $prev_loop_count = 0;
                                }
                                else {
                                    $row_counter = $prev_loop_count;
                                    $prev_loop_count = 0;
                                }
                            ?>
                        @endif
                    @endif
                @endforeach
            @endif
        </tbody>
    </table>

**Comment by catalinmv** [comment]
Hey, sorry to ask about this again, are there any updates on this issue? Any chances for this to be fixed in the next update?

**Comment by bsweeney** [comment]
Not the next update but there is work-in-progress to address the issue in the [paging-updates](https://github.com/dompdf/dompdf/tree/paging-updates) branch.

**Comment by tangchoozin** [comment]
Since it's still WIP, I will share how I achieve what I need. Not sure it will be helpful to other people but it's quite enough for me

![Screenshot 2023-12-16 at 10 20 12 AM](https://github.com/dompdf/dompdf/assets/8446366/f862caa9-a1c7-48d8-9230-88297ec64beb)

To achieve this, I need to remove all the rowspan in my `<td>`
Then at certain `<td>`, i have to use `border-bottom-color: transparent !important;` or `border-top-color: transparent !important;` or both

So i defined a class

```
.no-top-bottom {
	border-bottom-color: transparent !important;
	border-top-color: transparent !important;
}

.no-bottom {
	border-bottom-color: transparent !important;
}

.no-top {
	border-top-color: transparent !important;
}
```

Then the table content will be something like this. Can just loop it 10 or 20 times and play around with it

```
<tr>
	<td class="no-top-bottom"></td>
	<td class="no-top-bottom"></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td><br></td>
</tr>
<tr>
	<td class="no-top-bottom"></td>
	<td class="no-top-bottom"></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td><br></td>
</tr>
<tr>
	<td class="no-top-bottom"></td>
	<td class="no-bottom"></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td><br></td>
</tr>
<tr>
	<td class="no-top"></td>
	<td class="no-top"></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td><br></td>
</tr>
```

**Comment by aminankit31** [comment]
if we are using a static table then we can add a class to that particular row where the table breaks and we can apply CSS like 
tr.row-break {
  page-break-before: always;
}

**Comment by Doclassif** [comment]
This issue is still present. 2.0.1 version.

**Comment by Yahasana** [comment]
I must say that dompdf has so many bugs when render page break and very hard to fix.

**Comment by stblink** [comment]
Dont know if its of any help, but here is what happened to me and how i fixed it.

I have a small table with 6 columns and 9 rows... each 3 rows are grouped (rowspan) in 2 columns.
When in the first column i had number (ex: 1) it was all good with the cell borders, but when i had to iterate values (1 => January, etc) the cell boarder of the rowspan was inexistent except for the first cell rowspan.

When i defined manually the width of the first column (month) the cell borders showed up correctly.
So this is the cell that was affecting the borders:

`<td style="width:100px">{{ $monthNames[$month] }}</td>`

**Comment by mikaeldiok** [comment]
my current solution is make a td with no-border class, so it will imitates a rowspan. this works really well in my case where the table structure is very strict. this is the example when using foreach and nested foreach. hope this helps!

```
<html>
<head>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        tr, td, th {
            border: 1px solid black;
            page-break-inside: avoid;
        }
        .no-border {
            border: none;
        }
    </style>
</head>
<body>
    <table class="table-bordered">
        @foreach(.....)
            <tr>
                <td>...</td>
                <td >...</td>
            </tr>
            <tr>
                <td class="no-border"></td>
                <td>...</td>
                <td >...</td>
                <td >...</td>
                <td >...</td>
            </tr>
            @foreach(...)
                    <tr>
                        <td class="no-border"></td>
                        <td>...</td>
                        <td>...</td>
                        <td ...</td>
                        <td>...</td>
                    </tr>
            @endforeach
        @endforeach
    </table>
</body>
</html>
```

![image](https://github.com/user-attachments/assets/3cc65e07-6887-46e7-a576-633f43cf286b)

**Comment by crudagency** [comment]
Only add style
`@page {
            size: a4 portrait;
        }`

**Comment by mikaeldiok** [comment]
my solution is to remove the border of a table with css top-border and bottom-border, so it imitates the rowspan. there is still a problem to handle the last row though, maybe by checking if its the last element.

```
<table class="table-bordered">
    @foreach()
        <tr style="page-break-inside: avoid;">
            <td>..</td>
            <td colspan="4">..</td>
        </tr>
        <tr style="page-break-inside: avoid;">
            <td>..</td>
            <td>..</td>
            <td >..</td>
            <td>..</td>
            <td >..</td>
        </tr>
        @foreach()
                <tr style="page-break-inside: avoid;">
                    <td class="no-border">..</td>
                    <td>..</td>
                    <td >..</td>
                    <td >..</td>
                    <td >..</td>
                </tr>
        @endforeach
    @endforeach
</table>
```

![image](https://github.com/user-attachments/assets/ac38d491-e499-483d-a597-a0425a601761)

**Comment by branislavblazek** [comment]
Hi, is there any new update? I can see there just delaying milestones... and that branch what should fix this issue is 1+ year old...
