### ISSUE TITLE
Why float not working in laravel dompdf?

### ISSUE THREAD

**Issue by moschel26** [dompdf/dompdf#1450]
I use Laravel 5.3

I use :

> "barryvdh/laravel-debugbar": "^2.3",
> 
> "barryvdh/laravel-dompdf": "^0.7.0",
> 

I get from here : https://github.com/barryvdh/laravel-dompdf

In myapp\config\dompdf.php, I set :

> "DOMPDF_ENABLE_CSS_FLOAT" => true,

In my html pdf, I try : 

    <!DOCTYPE html>
    <html>
    	<head>
    		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    		<title>Test</title>
    
    		<style type="text/css"> 
    
    			body {  
    			    font-family: "Arial", Helvetica, sans-serif !important;
    			    font-size: 9px;
    			    margin-bottom: 100px;
    			}
    			.container {
    			    background:#fff;
    			    overflow:auto;
    			}
    
    			.left {float:left;}
    			.right {float:right;}
    
    		</style>
    
    		
    	</head>
    	<body>
    		<div class="container">
    		    <div class="left">Float left</div>
    		    <div class="right">Float right</div>
    		</div>
    	</body>
    </html>

The float not working

How can I solve it?

**Update** :

The result of pdf is like this : 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/CDH8Z.png

**Comment by cabeza-melon** [comment]
You are using v0.7. This has only been fixed in v0.8.

Change

```"barryvdh/laravel-dompdf": "^0.7.0",```

to

```"barryvdh/laravel-dompdf": "^0.7.0",```

and hopefully it should work.

**Comment by moschel26** [comment]
@cabeza-melon, Ok thanks. I will reinstall it. Btw, Whether display: flex also already exists?

**Comment by cabeza-melon** [comment]
This [is still open](https://github.com/dompdf/dompdf/issues/971), so: no.
As you can see [here](https://github.com/dompdf/dompdf/milestone/6) it is listed for the v0.8.1 milestone, so is scheduled for the next version, whenever that may be.

**Comment by moschel26** [comment]
@cabeza-melon, Okay. I had change to "barryvdh/laravel-dompdf": "^0.8.0", in composer.json. Then I do : composer update. But the float still not work.  Look at here : https://postimg.org/image/y3fl0e4wn/. Whether it successfully reinstall laravel-dompdf?

**Comment by cabeza-melon** [comment]
Looks like for some reason it could not install v0.8, because of some composer "minimum stability" settings. I thought v0.8 should be stable, but it looks like v0.8 stability is marked as dev.

It might help to change
`"minimum-stability": "stable"`
to
`"minimum-stability": "dev"`
in your composer.json.

I am not really sure, as I have never had anything to do directly with composer packages.

Anyway, as this is an issue with the usage of composer and not really with DomPDF itself anymore, it seems better to pursue follow-up questions on a place like [stackoverflow](http://stackoverflow.com).

**Comment by moschel26** [comment]
@cabeza-melon, minimum-stability not exist in my composer.json. I change "laravelcollective/html": "dev-master" to "laravelcollective/html": "^5.3.0", it works. Thanks a lot

**Comment by moschel26** [comment]
@cabeza-melon, overflow:auto; also can not work in "barryvdh/laravel-dompdf": "^0.8.0"? I had try it. But it does not work

**Comment by cabeza-melon** [comment]
I am not a maintainer or developer of this package. I just came here by coincidence and tried to answer your first question which seemed obvious to me.
I don't know anything else and cannot help you. Sorry.

**Comment by moschel26** [comment]
@cabeza-melon, I'm sorry to have to spend your time

**Comment by cabeza-melon** [comment]
No problem, I just wanted to explain.

**Comment by bsweeney** [comment]
Two things. First, Dompdf has float enabled by default starting with 0.7.0 so you don't need to modify the configuration to enable it.

Second, as of 0.7.0 we no longer use the configuration constants. So changing the value of `DOMPDF_ENABLE_CSS_FLOAT` does nothing. You'll want to pass in values on Dompdf instantiation or use the `$dompdf->set_option()` method.

Regarding your follow-up question, `overflow: auto;` is supported. What are you looking for that isn't working in your PDF?

**Comment by bsweeney** [comment]
@cabeza-melon thanks for the assist 🙌
