### ISSUE TITLE
Whitespace inside HTML tag breaks rendering

### ISSUE THREAD

**Issue by TobiasKappe** [dompdf/dompdf#1494]
It looks like adding whitespace between the HTML and HEAD tags breaks the renderer.

To reproduce this, run the following:

    use Dompdf\Dompdf;
    
    $dompdf = new DomPDF();
    
    $dompdf->load_html(<<<HTML
    <html>
    <head>
    </head>
    <body>
    Hello world
    </body>
    </html>
    HTML
    );
    
    $dompdf->render();

On my system (Arch Linux, PHP 7.1.7, DomPDF 0.8.0), I get the following exception:

    Fatal error: Uncaught Dompdf\Exception: No block-level parent found.  Not good. in <path>/dompdf/dompdf/src/Positioner/Inline.php:45
    Stack trace:
    #0 <path>/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(872): Dompdf\Positioner\Inline->position(Object(Dompdf\FrameDecorator\Text))
    #1 <path>/dompdf/dompdf/src/FrameReflower/Text.php(368): Dompdf\FrameDecorator\AbstractFrameDecorator->position()
    #2 <path>/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(893): Dompdf\FrameReflower\Text->reflow(NULL)
    #3 <path>/dompdf/dompdf/src/FrameReflower/Page.php(141): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
    #4 <path>/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(893): Dompdf\FrameReflower\Page->reflow(NULL)
    #5 <path>/dompdf/dompdf/src/Dompdf.php(831): Dom in <path>/dompdf/dompdf/src/Positioner/Inline.php on line 45

Removing the whitespace from `<html>` to `<head>`, `</head>` to `<body>` and `</body>` to `</html>` prevents the error.

**Comment by TobiasKappe** [comment]
On a PHP 7.0 installation, this problem does not occur (for me).

**Comment by simonberger** [comment]
That sounds strange.
Did you try that without the heredoc syntax?

Activating the HTML5 parser should fix this either.

**Comment by TobiasKappe** [comment]
Hi Simon,

Using quotes instead of heredoc makes no difference (and I'm not sure why it would).

Activating the HTML5 parser indeed prevents the problem. I would, however, argue that this behavior is still a bug. For instance, the problem still occurs when the HTML5 parser is not enabled, but the following (valid XHTML 1.0 strict) is passed:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <title>Test</title>
    </head>
    <body>
    <p>Hello world</p>
    </body>
    </html>

**Comment by bsweeney** [comment]
I'm not seeing the same issue on my system using Dompdf 0.8.0 with PHP 7.1.5. Possibly it's an issue with 7.1.7, but I'd need to set up a system with that to see. It could also be one of the system libraries that's causing the issue.

Generally, we recommend using the HTML5 parser because it can help prevent all kinds of parsing issues. I understand that's a work-around not a resolution. But unless we can definitely identify the cause we won't be able to resolve the issue.

If you have time it would help if you could identify precisely what is causing the issue. We've seen more requests for help with this issue lately. It's generally caused by one of two issues:

1. Dompdf attempting to parse a null HTML string.
2. The default stylesheet not loading correctly.

If you have time we can work with you to try to identify the exact cause.

**Comment by TobiasKappe** [comment]
Hi Brian,

From what I remember in my debugging attempts, what is happening is that the XML-tree that Dompdf is working with contains an additional "Text" element (which contains the whitespace) as a child of `<html>` and a predecessor to `<head>`. The layout engine is trying to style this element, and is unable to find a block-level parent for this tag, hence the exception.

If you have any questions about my system I'd be happy to answer. For instance, does Dompdf use a particular parsing-library that I could try to switch/downgrade/tweak to see if the issue persists? If you have any other experiments that could help you in fixing this problem, please let me know.

**Comment by bsweeney** [comment]
Dompdf doesn't use any particular libraries beyond the ones provided by PHP or your operating system. The main one at the point of parsing, with the HTML5 parser disabled, would be anything required by the DOM extension (i.e. libxml).

Since we have seen quite a few queries regarding the "No block level parent found" exception it might be worth investigating the particular issue around attempted styling of non-body content. But we won't be able to get very far unless I can reproduce the issue.

**Comment by TobiasKappe** [comment]
For what it's worth, I've been able to suppress the error with the following patch, which avoids reflowing `Text` children of the `Page`:
```diff
diff --git a/src/FrameReflower/Page.php b/src/FrameReflower/Page.php
index dc87705..a826ac8 100644
--- a/src/FrameReflower/Page.php
+++ b/src/FrameReflower/Page.php
@@ -11,6 +11,7 @@ namespace Dompdf\FrameReflower;
 use Dompdf\Frame;
 use Dompdf\FrameDecorator\Block as BlockFrameDecorator;
 use Dompdf\FrameDecorator\Page as PageFrameDecorator;
+use Dompdf\FrameDecorator\Text as TextFrameDecorator;
 
 /**
  * Reflows pages
@@ -138,7 +139,10 @@ class Page extends AbstractFrameReflower
                 }
             }
 
-            $child->reflow();
+            if (!($child instanceof TextFrameDecorator)) {
+                $child->reflow();
+            }
+
             $next_child = $child->get_next_sibling();
 
             // Check for begin render callback
```
The PDF generated from the code above has some superfluous empty pages though, so it is not a fix - merely a confirmation of my suspicion.

The version of libxml2 on my system is `2.9.4+96+gfb56f80e-1`, which corresponds to [this commit](https://github.com/GNOME/libxml2/tree/fb56f80eeffde4b79a49667c3f0727181d57aeb3)

**Comment by nakiom** [comment]
I have the same problem since I've upgrade to PHP 7.1.7 ("No block-level parent found. Not good."). Now I'm using PHP7.1.8 and DOMPDF v0.8.0 and still not working the render. 
I did what @TobiasKappe said on Page.php
So now the render is working, but my PDF now has two white and blank pages before and another empty page after "my document"

--blank page
--blank page
--my pdf render
--blank page

**Comment by Spreeuw** [comment]
Is there any potential downside to activating the HTML5 parser? What does this do exactly and why is it not enabled by default? Thanks!

**Comment by bsweeney** [comment]
There isn't really a downside. The main reason it's disabled is that the version currently included with the project is no longer maintained and has a few bugs. There's a maintained fork that we intend to include in the future but haven't had a chance to review the integration.

**Comment by burlap** [comment]
For me, this issue is caused by libxml2 version 2.9.5.

My results (PHP 5.6.31):

1. libxml2 2.9.5, enable_html5_parser => false, test.html  -> "Not good"
2. libxml2 2.9.5, enable_html5_parser => true, test.html -> ok
3. libxml2 2.9.5, enable_html5_parser => false, test_single_line.html -> ok
4. libxml2 2.9.5, enable_html5_parser => true, test_single_line.html -> ok
5. libxml2 2.9.4 - ok, for both test.html and test_single_line.html, regardless of the enable_html5_parser setting

test.html
```html
<!DOCTYPE html>
<html>
<head>
    <title>Foo</title>
</head>
<body>
    <p>hello world</p>
</body>
</html>
```

test_single_line.html
```html
<!DOCTYPE html><html><head><title>Foo</title></head><body><p>hello world</p></body></html>
```

Testing with:
```php
<?php
require 'vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();

$options->set('enable_html5_parser', true);

$options->set('chroot', 'path-to-test-html-files');

$dompdf = new Dompdf($options);

// test.html or test_single_line.html
$dompdf->loadHtmlFile('test.html');

$dompdf->setPaper('A4', 'landscape');

$dompdf->render();

$dompdf->stream();
?>
```

**Comment by bsweeney** [comment]
Thanks @burlap. So it does appear that this is potentially due to a change made between 2.9.4 and 2.9.5.

I'll have to see if I can set up a system to reproduce the issue. I may also review the change log and commit history for libxml to see if there's anything that stands out as a potential cause.

Can you post the format of the document after loading it (i.e. the return from `$dompdf->outputHtml();`)? Not sure if it'll provide any clues but it can't hurt.

**Comment by burlap** [comment]
1. 2.9.5, enable_html5_parser => false, test.html
```html
<!DOCTYPE html>
<html>

<head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Foo</title>
</head>

<body>
    <p>hello world</p>
</body>

</html>
```

2. 2.9.4, enable_html5_parser => false, test.html
```html
<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"><title>Foo</title></head><body>
    <p>hello world</p>
</body></html>
```

3. 2.9.5 and 2.9.4, enable_html5_parser => true, test.html
```html
<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Foo</title>
</head><body>
    <p>hello world</p>


</body></html>
```

There are no differences for test_single_line (as expected, it did work in all configs).

**Comment by windaishi** [comment]
I can confirm the problem with PHP 7.0.23 and libxml2 v2.7.6

This is working:
```
<html><head><meta http-equiv="content-type" content="text/html; utf-8" /><title>s</title></head><body><p>Hey</p></body></html>
```

This does fail with the error 'No block-level parent found.  Not good.'
```
<html>
<head><meta http-equiv="content-type" content="text/html; utf-8" /><title>s</title></head><body><p>Hey</p></body></html>
```

**Comment by helmutschneider** [comment]
Experiencing this on OSX with 7.1.8 & libxml 2.9.4. I managed to get by with this ugly regex to remove whitespace between tags:
```php
$html = preg_replace('/>\s+</', '><', $html);
```

**Comment by bluefirex** [comment]
This issue was bugging me today, too. Using the fix @helmutschneider posted (removing whitespaces) helped.

**Comment by steffenweber** [comment]
I can confirm that this issue can be solved by downgrading libxml2 from version 2.9.5 to version 2.9.4 or by applying the workaround posted by @helmutschneider (thank you!).

(Using PHP 7.1.8 on Linux.)

**Comment by koseduhemak** [comment]
I can confirm that this issue is also present on Mac OSX PHP 7.1.8 with libxml >= 2.9.5 (installed via brew). Downgrading to libxml 2.9.4 worked as @steffenweber already stated. Workaround by @helmutschneider for libxml >= 2.9.5 solves the problem somehow, but is quite hackish. Any better solution is appreciated.

**Comment by Spreeuw** [comment]
I think enabling the HTML5 Parser is by default is the way forward
``` php
$options->setIsHtml5ParserEnabled( true );
```
Although that library should definitely be updated. Anything holding off from integrating https://github.com/Masterminds/html5-php/ instead of https://github.com/html5lib/html5lib-php/ (over 8 years old)?

**Comment by ciromattia** [comment]
@Spreeuw on macOS (libxml 2.9.5, PHP 7.0.22) the issue is happening even with HTML5 Parser enabled.

**Comment by windaishi** [comment]
In a previous post I wrote that the problem happens with version 2.7.6 of libxml2. I found out that it actually was 2.9.5. But the PHP-Version was compiled against 2.7.6 and therefore was showing this version in PHP-Info and also in the LIBXML_VERSION constant. But PHP was actually loading libxml 2.9.5. Thats why the error occured even PHP showed that it had libxml2 in version 2.7.6.
So i can confirm that it is a 2.9.5 bug.
Also, the workaround posted in this thread worked for me.

**Comment by TobiasKappe** [comment]
As of DomPDF 0.8.1, this issue occurs even when the HTML5 parser is enabled.

So, to summarise:
- DomPDF 0.8.0, HTML5 parser disabled: error
- DomPDF 0.8.0, HTML5 parser enabled: works
- DomPDF 0.8.1, HTML5 parser disabled: error
- DomPDF 0.8.1, HTML5 parser enabled: error

This is on PHP 7.1.9 and libxml 2.9.5.

**Comment by DavidAnderson684** [comment]
Does the issue exist with libxml 2.9.6 (the latest)? There's a changelog entry (https://git.gnome.org/browse/libxml2/log/), "Fix structured validation errors".

**Comment by steffenweber** [comment]
Upgrading from libxml2 2.9.5 to 2.9.6 does not change anything here: works only with the workaround.

**Comment by garnold** [comment]
Heads-up, Google just upgraded the Google App Engine Standard Environment PHP 5.5 build (**Build Date | Sep 28 2017 10:04:45**) to libxml 2.9.5 and this issue immediately bit us. Setting `isHtml5ParserEnabled = true` fixed the issue.

**Comment by bsweeney** [comment]
@garnold thanks for the feedback. Hopefully we can switch out our HTML5 parser in one of the upcoming releases.

**Comment by ixperiencenl** [comment]
Is this issue now resolved or are we still experiencing exporting problems atm?

**Comment by Spreeuw** [comment]
@ixperiencenl afaik this issue hasn't resolved itself, although #1570 seems to be a reliable fix
@bsweeney anything holding you off from applying #1570?

**Comment by bsweeney** [comment]
Just time. There are a few issues slated for a 0.8.2 release, I'll try to pare them down to the bare minimum of bug fixes.

**Comment by bsweeney** [comment]
I merged #1570. I still need to see if I can find a testable setup.

**Comment by MuzaffarMahmood** [comment]
It was working fine with php5.5.12 but on changing php version to 7.0.25 it stopped working and throwing this error.

An uncaught Exception was encountered

Type: DOMPDF_Exception

Message: No block-level parent found. Not good.

Filename: D:\wamp\www\ci316\application\libraries\dompdf\include\inline_positioner.cls.php

Line Number: 37


How to resolve this????

**Comment by ixperiencenl** [comment]
For now I fixed it with removing the package (and the cache fonts!) and re-installing it. And it's important to filter the output you want to let the PDF parse. Example: `$content = preg_replace('/>\s+</', '><', $content);`

**Comment by xxRockOnxx** [comment]
@ixperiencenl's solution is a lucky 2-in-1 fix!

A colleague added that line to fix the bug that solution is intended for but it also fixed one of the weird issue we have! It was on a separate branch that time.

On local, everything is fine, but on the server, it has some inconsistency in layout; overlapping elements, line-height issues, etc.

Spent hours debugging and looking for answers (that nobody seems to have), but after many hours, I tried adding that line and it worked.

After merging the branch, 2 of potential problem went away.

**Comment by garnold** [comment]
@bsweeney Is this fixed? Or should we just stick with the remove whitespace workaround?

**Comment by bsweeney** [comment]
The patch is now pushed to the master branch so if you're pulling for there you can update. If you're waiting for a tagged release I should have 0.8.2 ready sometime this week.

**Comment by bsweeney** [comment]
FYI 0.8.2 is out.

**Comment by alexmiller00** [comment]
> Experiencing this on OSX with 7.1.8 & libxml 2.9.4. I managed to get by with this ugly regex to remove whitespace between tags:
> 
> ```
> $html = preg_replace('/>\s+</', '><', $html);
> ```

This was all it took after a little tinkering ( also I am running libxml2-2.9.1-6.e17_2_3.x86_64, and i have the 'isHtml5ParserEnabled' = true)


code.....
`use Dompdf\Options;
$dompdf = new Dompdf();

// instantiate and use the dompdf class
$options = new Options();

$options->set('enable_html5_parser', true);

$dompdf->set_option('isHtml5ParserEnabled', true);
$contents = $html = preg_replace('/>\s+</', '><', $contents);
$dompdf->loadHtml($contents);`

**Comment by Zokor** [comment]
This $html = preg_replace('/>\s+</', '><', $html); answer is still up to date today.

Was having issues with space in the paragraphs. This fixed them.

Thank you
