### ISSUE TITLE
Can't create a page with 4 equals squares

### ISSUE THREAD

**Issue by Defacta** [dompdf/dompdf#2468]
Hello,

I try to create a A4 page with 4 equals parts.

I tried with inline div and with table but with no success.

With tables:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<title>Header and Footer example</title>
<style type="text/css">
* {
    margin:0;
    padding:0;
}
@page {
  margin: 0;
}
.bg-red {
  background:red;
}
.bg-green {
  background:green;
}
.bg-grey {
  background:#ddd;
}
</style>
</head>
<body>
<table class="bg-red" style="width:100%;line-height:0;" cellspacing="0" cellpadding="0">
<tr>
  <td class="bg-grey" style="width:50%;height:50%;line-height:0;">Square 1</td>
  <td class="bg-green" style="width:50%;height:50%;line-height:0;">Square 2</td>
</tr>
<tr>
  <td class="bg-green" style="width:50%;height:50%;line-height:0;">Square 3</td>
  <td class="bg-grey" style="width:50%;height:50%;line-height:0;">Square 4</td>
</tr>
</table>
</body>
</html>
```
Result:
![image](https://user-images.githubusercontent.com/18191463/120512433-a5100500-c3cb-11eb-9e2a-98f1b7b850a4.png)

Is there any chance to do it?

If I try with height at 49%, there is a big white line at the bottom of the page.

Thanks,
Vincent.

**Comment by bsweeney** [comment]
This rendered as expected when I ran it through my test bed. Which version of Dompdf are you using?

**Comment by Defacta** [comment]
> This rendered as expected when I ran it through my test bed. Which version of Dompdf are you using?

1.0.2 and I also tried on 0.8.5.

To construct the package I did:
```
git clone https://github.com/dompdf/dompdf/
cd dompdf/
composer install --no-dev --optimize-autoloader
```

To create the PDF I do:

```
require_once (__DIR__.'/'._PATHROOT.'include/php/0_libraries/pdf/dompdf/1.0.2/vendor/autoload.php');

$options = new \Dompdf\Options();
$options->set('isRemoteEnabled', true);
$options->set('isPhpEnabled', true);
$dompdf = new \Dompdf\Dompdf($options);
$dompdf->set_option('dpi', 300);
$dompdf->set_paper('A4', 'portrait');

$html = '...';

$dompdf->load_html($html);
$dompdf->render();
$output = $dompdf->output();
file_put_contents('test.pdf', $output);
```

**Comment by Defacta** [comment]
What is strange is I do that:

```
<table>
  <tr>
    <td class="bg-red" height="200px" width="200px">
      <table>
        <tr>
          <td class="bg-green" height="50%" width="200px">
          </td>
      </table>
    </td>
  </tr>
</table>
```

The second cell bg-green of the second table should have a height of 50% of 200px, so 100px, but the height is 50% of the entire page instead of the td in which the table is.
It's like it does not inherit of the parent height and takes 50% of all the page. Is it normal?
![image](https://user-images.githubusercontent.com/18191463/120521790-4cde0080-c3d5-11eb-8483-4a9fdcdc9fa7.png)

**Comment by bsweeney** [comment]
The second issue you noted is probably related to #2255. It could be implicated in the issue you have rendering the document. If possible, an absolute unit may give you more consistent results.

**Comment by Nexample-G** [comment]
Your Solution here
https://youtu.be/wcAoC8P5gaM

**Comment by Mellthas** [comment]
This is fixed by the changes to handling empty text nodes in #1356. The issue can be worked around by removing the whitespace between the `body` and `table` tags (and fixing the spelling of `</boyd>` :-)).

**Comment by bsweeney** [comment]
Regarding that last sample, the inner height should be on the table element instead of the cell. This is because the block formatting context for the cell is the table, which has no height. Dompdf is still wrong, but the rendering should be no height instead of that indicated in your comment.

Also, Dompdf does not current support the height attribute on table elements, so you should use a style attribute instead.

The following is rendered correctly:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<title>Header and Footer example</title>
<style type="text/css">
* {
    margin:0;
    padding:0;
}
@page {
  margin: 0;
}
.bg-red {
  background:red;
}
.bg-green {
  background:green;
}
.bg-grey {
  background:#ddd;
}
</style>
</head>
<body>
    <table>
        <tr>
          <td class="bg-red" height="200px" width="200px">
            <table style="height:50; width:200px">
              <tr>
                <td class="bg-green">
                </td>
            </table>
          </td>
        </tr>
      </table>
      </body>
</html>
```
