### ISSUE TITLE
Fix for undefined method DOMText::getAttribute() in cellmap.cls.php

### ISSUE THREAD

**Issue by dleffler** [dompdf/dompdf#895]
Here is a fix for the fatal error 'undefined method DOMText::getAttribute() in cellmap.cls.php' resulting from an invalid table (table includes text outside of a cell)

Edit /include/cellmap.cls.php to add a conditional statement about those lines that attempt to get/set a colspan/rowspan attribute
- at line 436 (before/after the '//Determine where this cell is going' comment) insert the following line

```
   if (get_class($node) != 'DOMText') {
```
- and above the line '$key = $frame->get_id();' insert a closing brace

```
    }
```

**Comment by bsweeney** [comment]
That would do it. Do you have some sample code? Looks to be related to issue #74 and likely to be encountered when there are structural errors. Still, we should catch for issues like this when we can.

Also note that if the problem is due to structural issues enabling the HTML5 parser could help. Also watch issue #449.

**Comment by AJMiller** [comment]
@dleffler Just wanted to say thank you for this patch! Spent a full day with DOMPDF spitting out this error and unable to figure out why it was getting caught up on those lines. Finally tried this patch and it rendered the PDFs perfectly. Difficult issue to debug because the DOMPDF debug tool was able to take the same HTML and render it into a PDF perfectly fine. It only failed on our development server. Thanks again!

**Comment by raxhet91** [comment]
if I put that code it give me an error Undefined variable: rowspan how can i solve that?

**Comment by dleffler** [comment]
The above fix prevents (0.6.x) the fatal error by skipping that code section if there is a DOMText node within a table (which if properly constructed shouldn't be there). In 0.7.0 the code has moved to /lib/Celmap.php and is located around lines # 558 to 569.

**Comment by raxhet91** [comment]
I've the 0.6.* but if I insert that code, it's not working!!! how can I solve that?
________________________________
Da: dleffler <notifications@github.com>
Inviato: sabato 28 maggio 2016 12.14
A: dompdf/dompdf
Cc: raxhet91; Comment
Oggetto: Re: [dompdf/dompdf] Fix for undefined method DOMText::getAttribute() in cellmap.cls.php (#895)


The above fix prevents (0.6.x) the fatal error by skipping that code section if there is a DOMText node within a table (which if properly constructed shouldn't be there). In 0.7.0 the code has moved to /lib/Celmap.php and is located around lines # 558 to 569.

-

**Comment by dleffler** [comment]
Old code looks like

// Determine where this cell is going
$colspan = $node->getAttribute("colspan");
$rowspan = $node->getAttribute("rowspan");

if ( !$colspan ) {
  $colspan = 1;
  $node->setAttribute("colspan",1);
}

if ( !$rowspan ) {
  $rowspan = 1;
  $node->setAttribute("rowspan",1);
}
$key = $frame->get_id();

 

Fixed code looks like

// Determine where this cell is going
if (get_class($node) != 'DOMText') {
$colspan = $node->getAttribute("colspan");
$rowspan = $node->getAttribute("rowspan");

if ( !$colspan ) {
   $colspan = 1;
   $node->setAttribute("colspan",1);
}

if ( !$rowspan ) {
   $rowspan = 1;
   $node->setAttribute("rowspan",1);
}
}
$key = $frame->get_id();

 

So the warning? you’re getting can not be a result of this code unless you inserted something other than ‘!=’. I found my fix by using xdebug and my IDE (PHPStorm) to determine the $node was not from a table since it was a DOMText class.  You might try the same to see what class $node is when the warning occurs?

 

Dave Leffler

**Comment by raxhet91** [comment]
yes. the code is like that... when i insered that it gave me an error undefined variable rowspan

**Comment by bsweeney** [comment]
@raxhet91 First thing you might do is either a) check your HTML for structural errors (e.g. using the w3 validator), or b) enable the HTML5 parser. Dompdf isn't very forgiving of structural problems in the HTML.

If that doesn't work you should consider upgrading to 0.7.0 which has an update that can address this issue (see commit 9af6eab022f9ba63d5c469ead272e8d8f6cb33e4).

@dleffler I don't think this patch is necessary in 0.7.0 anymore, can you confirm?

**Comment by bsweeney** [comment]
Closing since I haven't heard otherwise. If this is still an issue please post an update.

**Comment by wreardan** [comment]
I am still having this problem.  I was able to fix the issue by using `$dompdf->set_option('isHtml5ParserEnabled', true);`

**Comment by bsweeney** [comment]
@garrettw best time to set options is before you load your document, so something like ...

```
$dompdf = new Dompdf();
$dompdf->setOption('isHtml5ParserEnabled', true);
```

@wreardan sounds like potentially invalid HTML is causing the issue. If you can provide a sample we can confirm. I generally recommend using the HTML5 parser if you can. It's not enabled by default because we're using a fairly old version right now.

**Comment by garrettw** [comment]
@bsweeney oh I just realized I'm asking the wrong people. I'm using this library in the context of Drupal's print module. 🤦‍♂️
